-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665.2
--   at:        2011-11-25 22:41:11 COT
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



CREATE TABLE Almacen
    (
     idAlmacen NUMBER (10)  NOT NULL ,
     nombre VARCHAR2 (30) ,
     direccion VARCHAR2 (40)
    )
;



ALTER TABLE Almacen
    ADD CONSTRAINT Almacen_PK PRIMARY KEY ( idAlmacen ) ;


CREATE TABLE Cliente
    (
     idCliente NUMBER (10)  NOT NULL ,
     nombre VARCHAR2 (40) ,
     tarjetaCliente NUMBER (10)  NOT NULL
    )
;



ALTER TABLE Cliente
    ADD CONSTRAINT Cliente_PK PRIMARY KEY ( idCliente ) ;

ALTER TABLE Cliente
    ADD CONSTRAINT Cliente__UN UNIQUE ( tarjetaCliente ) ;


CREATE TABLE Empleado
    (
     idEmpleado NUMBER (10)  NOT NULL ,
     nombre VARCHAR2 (40) ,
     edad INTEGER ,
     Almacen_idAlmacen NUMBER (10)  NOT NULL
    )
;



ALTER TABLE Empleado
    ADD CONSTRAINT Empleado_PK PRIMARY KEY ( idEmpleado ) ;


CREATE TABLE Producto
    (
     idProducto NUMBER (10)  NOT NULL ,
     nombre VARCHAR2 (40) ,
     precio NUMBER (12,2)
    )
;



ALTER TABLE Producto
    ADD CONSTRAINT Producto_PK PRIMARY KEY ( idProducto ) ;


CREATE TABLE Venta
    (
     numero NUMBER (10)  NOT NULL ,
     fecha DATE ,
     totalVenta NUMBER (12,2) ,
     Empleado_idEmpleado NUMBER (10)  NOT NULL ,
     estado CHAR (1) ,
     Cliente_idCliente NUMBER (10)  NOT NULL
    )
;



ALTER TABLE Venta
    ADD CONSTRAINT Venta_PK PRIMARY KEY ( numero ) ;


CREATE TABLE auditoria
    (
     nro INTEGER  NOT NULL ,
     idEmpleado NUMBER (10) ,
     fechaHora DATE ,
     accion VARCHAR2 (40) ,
     idRegistro NUMBER (10)
    )
;



ALTER TABLE auditoria
    ADD CONSTRAINT auditoria_PK PRIMARY KEY ( nro ) ;


CREATE TABLE inventarioAlmacen
    (
     Producto_idProducto NUMBER (10)  NOT NULL ,
     Almacen_idAlmacen NUMBER (10)  NOT NULL ,
     cantidad NUMBER
    )
;



ALTER TABLE inventarioAlmacen
    ADD CONSTRAINT inventarioAlmacen_PK PRIMARY KEY ( Producto_idProducto, Almacen_idAlmacen ) ;


CREATE TABLE itemVenta
    (
     Venta_numero NUMBER (10)  NOT NULL ,
     Producto_idProducto NUMBER (10)  NOT NULL ,
     cantidad INTEGER ,
     descuento NUMBER (12,2) ,
     estado CHAR (1)
    )
;



ALTER TABLE itemVenta
    ADD CONSTRAINT itemVenta_PK PRIMARY KEY ( Venta_numero, Producto_idProducto ) ;


CREATE TABLE tarjetaCliente
    (
     numero NUMBER (10)  NOT NULL ,
     puntos INTEGER
    )
;



ALTER TABLE tarjetaCliente
    ADD CONSTRAINT tarjetaCliente_PK PRIMARY KEY ( numero ) ;



ALTER TABLE Cliente
    ADD CONSTRAINT Cliente_tarjetaCliente_FK FOREIGN KEY
    (
     tarjetaCliente
    )
    REFERENCES tarjetaCliente
    (
     numero
    )
;


ALTER TABLE Empleado
    ADD CONSTRAINT Empleado_Almacen_FK FOREIGN KEY
    (
     Almacen_idAlmacen
    )
    REFERENCES Almacen
    (
     idAlmacen
    )
;


ALTER TABLE Venta
    ADD CONSTRAINT Venta_Cliente_FK FOREIGN KEY
    (
     Cliente_idCliente
    )
    REFERENCES Cliente
    (
     idCliente
    )
;


ALTER TABLE Venta
    ADD CONSTRAINT Venta_Empleado_FK FOREIGN KEY
    (
     Empleado_idEmpleado
    )
    REFERENCES Empleado
    (
     idEmpleado
    )
;


ALTER TABLE inventarioAlmacen
    ADD CONSTRAINT inventarioAlmacen_Almacen_FK FOREIGN KEY
    (
     Almacen_idAlmacen
    )
    REFERENCES Almacen
    (
     idAlmacen
    )
;


ALTER TABLE inventarioAlmacen
    ADD CONSTRAINT inventarioAlmacen_Producto_FK FOREIGN KEY
    (
     Producto_idProducto
    )
    REFERENCES Producto
    (
     idProducto
    )
;


ALTER TABLE itemVenta
    ADD CONSTRAINT itemVenta_Producto_FK FOREIGN KEY
    (
     Producto_idProducto
    )
    REFERENCES Producto
    (
     idProducto
    )
;


ALTER TABLE itemVenta
    ADD CONSTRAINT itemVenta_Venta_FK FOREIGN KEY
    (
     Venta_numero
    )
    REFERENCES Venta
    (
     numero
    )
;












-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- ERRORS                                   0
-- WARNINGS                                 0
