SET ECHO OFF
SET VERIFY OFF

PROMPT Especifique un usuario como parametro número 0:
DEFINE us     = &0

PROMPT
PROMPT Especifique una contraseña como parametro 1:
DEFINE pass     = &1

DEFINE tbs      =USERS
DEFINE ttbs     =TEMP

CREATE USER &us IDENTIFIED BY &pass;

ALTER USER &us DEFAULT TABLESPACE &tbs
              QUOTA UNLIMITED ON &tbs;

ALTER USER &us TEMPORARY TABLESPACE &ttbs;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO &us;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO &us;
