
CREATE TABLE VEHICLE (
  AUTO_MOBILE VARCHAR(20) PRIMARY KEY,
  CATEGORY VARCHAR(20)
);


 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Motor Vehicle', null);
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Four Wheeler', 'Motor Vehicle');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Two Wheeler', 'Motor Vehicle');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Motor Bikes', 'Two Wheeler');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Bicycles', 'Two Wheeler');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Cars', 'Four Wheeler');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Truck', 'Four Wheeler');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Hatchback', 'Cars');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Sedan', 'Cars');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Maruti Baleno', 'Hatchback');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Tata Altroz', 'Hatchback');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Hyundai Verna', 'Sedan');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Honda City', 'Sedan');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Yamaha MT09', 'Motor Bikes');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Triumph Tiger 800', 'Motor Bikes');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Fuji Bike', 'Bicycles');
 INSERT INTO VEHICLE (AUTO_MOBILE, CATEGORY) VALUES ('Giant Bicycle', 'Bicycles');
;